config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts do
    scope module: :posts do
      resources :comments
    end
  end
  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_one_attached :image
  broadcasts inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < ApplicationController
    before_action :set_post
    def new
      @comment = @post.comments.new
    end

    def create
      @comment = @post.comments.new(comment_params)
      @comment.user = current_user
      if @comment.save
        redirect_to root_path, notice: "Comment was created successfully"
      else
        render :new
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new 
    @post = Post.new
  end

  def create
    if @post = Post.create(post_params)
      redirect_to root_path, notice: "Post was created successfully!"
    else
      render :new
    end
  end

  private


  def post_params
    params.require(:post).permit(:caption, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<%= turbo_stream_from :posts %>
<div class="w-full flex flex-col">
  <h1 class="text-4xl text-gray-900"> Welcome Home </h1>
  
  <br/>

  <%= turbo_frame_tag :new_post do %>
    <%= link_to "New Post", new_post_path, class: "bg-gradient-to-r from-indigo-500 to-purple-500 text-indigo-50 rounded-lg shadow-md p-3" %>
  <% end %>

  <br/>

  <div id="posts" class="grid gap-8 h-full">
    <%= render partial: "posts/post", collection: @posts %>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IgClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="w-full">
  <div class="text-gray-700">
    <% if post.image.attached? %>
      <%= image_tag post.image, class: "h-64 object-cover" %>
    <% else %>
      <span class="text-gray-100"> No image was attached </span>
    <% end %>
    <h3 class="text-gray-700 text-2xl"> <%= post.caption %> </h3>
    <p class="text-gray-600 text-lg"> posted <%= time_ago_in_words post.created_at %> ago </p>
    <%= turbo_frame_tag dom_id(post, :comments) do %>
      <%= link_to new_post_comment_path(post) do %>
        <div class="flex">
          <span class="text-gray-600"> <%= post.comments.count %> comments </span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/comments/new.html.erb
<%= turbo_frame_tag dom_id(@post, :comments) do %>
  <%= form_with model: [@post, @comment] do |f| %>
    <div class="flex flex-col">
      <%= f.label :body %>
      <%= f.text_area :body, autofocus: true %>
    </div>
    <br/>
    <div class="flex items-center gap-4">
      <%= f.submit class: "bg-blue-500 text-blue-100 rounded-lg p-2 cursor-pointer" %>
      or
      <%= link_to "Cancel", root_path, class: "text-gray-700" %>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= turbo_frame_tag :new_post do %>
  <div class="max-w-2xl w-full rounded-lg">
    <%= form_with model: @post do |f| %>
      <div class="flex flex-col">
        <%= f.label :caption %>
        <%= f.text_field :caption %>
      </div>
      
      <div class="flex flex-col">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

      <br/>

      <%= f.submit class: "bg-blue-500 text-blue-100 rounded-lg px-3 py-2" %>
    <% end %>
  </div>
<% end %>